<a href="https://colab.research.google.com/github/Kasfim/CSE-413/blob/main/Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Use numpy to create a 3×3 matrix of random integers between 1 and 50.
# Run the code twice
# With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.
# Without setting a seed, allowing random values to change each time.

import numpy as np

np.random.seed(10)
matrix1 = np.random.randint(1, 51, size=(3, 3))
print("Matrix with fixed seed:\n", matrix1)

matrix2 = np.random.randint(1, 51, size=(3, 3))
print("\nMatrix without fixed seed:\n", matrix2)


Matrix with fixed seed:
 [[10 37 16]
 [ 1 50 29]
 [26 30 49]]

Matrix without fixed seed:
 [[30 50  9]
 [10  1 43]
 [41 37 17]]


In [ ]:
# Observe and explain the differences in outputs.  (in a different cell as text)
1.With a Fixed Seed (np.random.seed(10)):

->The random numbers are always the same every time you run the code.

->This makes your results consistent and repeatable.

2.Without Setting a Seed:

->The random numbers change every time you run the code.

->This gives you different results each time, adding variability.