<a href="https://colab.research.google.com/github/Kasfim/CSE-413/blob/main/ID_2215151110.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Use numpy to create a 3×3 matrix of random integers between 1 and 50.
# 1.Run the code twice

import numpy as np

matrix_a = np.random.randint(1, 51, size=(3, 3))
print("First Matrix A:\n", matrix_a)

matrix_b = np.random.randint(1, 51, size=(3, 3))
print("\nSecond Matrix B:\n", matrix_b)


First Matrix A:
 [[13 43 42]
 [24 23 30]
 [ 6 22 28]]

Second Matrix B:
 [[45 24 23]
 [21 48 39]
 [ 2 44 26]]


In [2]:
# 2. With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.

np.random.seed(10)
matrix_a = np.random.randint(1, 51, size=(3, 3))
print("First Matrix A:\n", matrix_a)

matrix_b = np.random.randint(1, 51, size=(3, 3))
print("\nSecond Matrix B:\n", matrix_b)


First Matrix A:
 [[10 37 16]
 [ 1 50 29]
 [26 30 49]]

Second Matrix B:
 [[30 50  9]
 [10  1 43]
 [41 37 17]]


In [3]:
# 3. Without setting a seed, allowing random values to change each time.

matrix_a = np.random.randint(1, 51, size=(3, 3))
print("First Matrix A:\n", matrix_a)

matrix_b = np.random.randint(1, 51, size=(3, 3))
print("\nSecond Matrix B:\n", matrix_b)


First Matrix A:
 [[37 48 12]
 [25 44 34]
 [ 9 37 15]]

Second Matrix B:
 [[50 14  6]
 [14 26 14]
 [29 23 31]]


In [ ]:
# 4.Observe and explain the differences in outputs.  (in a different cell as text)
1.With a Fixed Seed (np.random.seed(10)):

->The random numbers are always the same every time you run the code.

->This makes your results consistent and repeatable.

2.Without Setting a Seed:

->The random numbers change every time you run the code.

->This gives you different results each time, adding variability.